# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

//登录
POST http://{{host}}:{{port}}/admin/login
Content-Type: application/json

{
  "userName": "pc859107393",
  "pwd": "9945685a392931fc746b0c5023427481"
}

###

//获取管理员信息
GET http://{{host}}:{{port}}/admin
token:24ba74709912317d53d6e27a99cc4165

###

//获取管理员列表
GET http://{{host}}:{{port}}/admin/page/1
token:c76897c0ae348756495ee9d202ef4707

###


//获取菜单权限列表
GET http://{{host}}:{{port}}/admin/menus
token:d0896f7daea3d206f25692471767caee

###


//刷新菜单，权限验证
GET http://{{host}}:{{port}}/admin/notifyMenu
token:7b70ace5b91cd53454fdbaec313bd474

###


//刷新菜单，权限验证
GET http://{{host}}:{{port}}/admin/getAllFromCache
token:7b70ace5b91cd53454fdbaec313bd474

###

