# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

//登录
POST http://{{host}}:{{port}}/admin/login
Content-Type: application/json

{
  "userName": "pc859107393",
  "pwd": "9945685a392931fc746b0c5023427481"
}

###

//获取管理员信息
GET http://{{host}}:{{port}}/admin
token:2fb63f2163c431f5218a1b2515d02cd0

###

//获取管理员列表
GET http://{{host}}:{{port}}/admin/page/2
token:2fb63f2163c431f5218a1b2515d02cd0

###


//获取菜单权限列表
GET http://{{host}}:{{port}}/admin/menus
token:2fb63f2163c431f5218a1b2515d02cd0

###


//刷新菜单，权限验证
GET http://{{host}}:{{port}}/admin/notifyMenu
token:2fb63f2163c431f5218a1b2515d02cd0

###


//刷新菜单，权限验证
GET http://{{host}}:{{port}}/admin/getAllFromCache
token:2fb63f2163c431f5218a1b2515d02cd0

###

