# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

//登录
POST http://{{host}}:{{port}}/admin/login
Content-Type: application/json

{
  "userName": "pc859107393",
  "pwd": "9945685a392931fc746b0c5023427481"
}

###

//获取管理员信息
GET http://{{host}}:{{port}}/admin
token:87b48e68d3c204c2a956356019ec0d5f

###

//获取管理员列表
GET http://{{host}}:{{port}}/admin/page/1
token:bc2a1addb1a6afc4867aab1641ac632d

###


//获取菜单权限列表
GET http://{{host}}:{{port}}/admin/menus
token:5cf6d8632fc9a05971a90527678b890e

###

